### ISSUE TITLE
Kernel 4.2 problem

### ISSUE THREAD

**Issue by draft1** [longsleep/bcmwl-ubuntu#7]
Building initial module for 4.2.0-040200-generic
Error! Bad return status for module build on kernel: 4.2.0-040200-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.

**Comment by draft1** [comment]
DKMS make.log for bcmwl-6.30.223.248+bdcom for kernel 4.2.0-040200-generic (x86_64)
Fri Sep  4 05:22:56 PHT 2015
make: Entering directory '/usr/src/linux-headers-4.2.0-040200-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/built-in.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_linux.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c: In function ‘wl_notify_connect_status’:
/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:2075:4: error: too few arguments to function ‘cfg80211_discon$
    cfg80211_disconnected(ndev, 0, NULL, 0, GFP_KERNEL);
    ^
In file included from /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:33:0:
include/net/cfg80211.h:4584:6: note: declared here
 void cfg80211_disconnected(struct net_device _dev, u16 reason,
      ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o' failed
make[1]: *_\* [/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o] Error 1
Makefile:1386: recipe for target '_module_/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build' failed
make: **\* [_module_/var/lib/dkms/bcmwl/6.30.223.248+bdcom/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.2.0-040200-generic'

**Comment by draft1** [comment]
Can you please provide a fix .deb file for this?

**Comment by s7dhansh** [comment]
Please use branch linux-4.2. You may need to change the license to GPL.

**Comment by draft1** [comment]
How to use it? I'm not that expert to be able to install the zip file, I hope there's .deb file that I can use.

**Comment by longsleep** [comment]
See https://github.com/longsleep/bcmwl-ubuntu/issues/6#issuecomment-129772346 and the README how to your own package for Kernel 4.2. I am not providing package for Kernel 4.2 as it currently means to fake the license of bcmwl.

**Comment by longsleep** [comment]
@RoldanLT if you use Ubuntu 15.10 you no longer need my patched version. For older Ubuntu versions you can install the  Ubuntu mainline Kernel 4.2 and use my ppa (https://launchpad.net/~longsleep/+archive/ubuntu/bcmwl) which i just updated for 15.04 and 14.04.

**Comment by draft1** [comment]
Why it is not needed anymore for 15.10?
I'm not using it until it goes stable :).

I'm still on 15.04, and nice to see you update your package now on PPA :).

So I will remove your PPA package once I upgrade to 15.10 this October?

**Comment by draft1** [comment]
I maybe off topic, but this error only happen with me on Latest Kernel: http://askubuntu.com/questions/636238/error-cannot-find-a-backlight-controller
Maybe you have some thoughts on it?

Thanks!

**Comment by longsleep** [comment]
@RoldanLT : Ubuntu 15.10 does include Kernel 4.2 and thus has all the patches for bcmwl to support Kernel 4.2. The PPA might be required again when Kernel 4.3 comes out. The backlight controller issue is probably some incompatibility with the AMD proprietary drivers and newer Kernels.

**Comment by draft1** [comment]
Wow! Didn't know about that.
Thanks for your time and knowledge :).

One thing, If I upgrade my current Ubuntu 15.04 desktop now to 15.10 using the latest build.
Is it safe and also possible to upgrade when final stable comes out?

**Comment by longsleep** [comment]
Yes when you update now you will be on 15.10 repositories and receive all the fixes for stable automatically. Note that Ubuntu 15.10 is beta quality and you have to expect problems.

**Comment by draft1** [comment]
Ok, running this now :+1: 
sudo do-release-upgrade -d
